---
title: "EDA"
output: github_document
date: "2024-10-03"
---

```{r setup, message=FALSE}
library(tidyverse)
library(haven)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) |>
  select(name, id, everything())

```
```{r}
weather_df %>% 
  ggplot(aes(x = prcp))+
  geom_histogram()
```
```{r}
weather_df |> 
  filter(prcp >= 1000)
```

```{r}
weather_df %>% 
  filter(tmax > 20, tmax < 30) %>% 
  ggplot(aes(x = tmin, y = tmax, color = name))+
  geom_point()
```
## group_by()
```{r}
weather_df %>% 
  group_by(name, month)
```
counting stuff
```{r}
weather_df %>% 
  group_by(name) %>%
  summarize(
    n_obs = n(),
    n_dist = n_distinct(month)
            )
```
```{r}
weather_df %>% 
  count(name)
```
summarize()
```{r}
weather_df |>
  group_by(month) |>
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE),
    mean_prec = mean(prcp, na.rm = TRUE),
    median_tmax = median(tmax, na.rm = TRUE),
    sd_prcp = sd(prcp, na.rm = TRUE)
    ) 
```
lag() creates a copy and shift the entries down by 1
```{r}
weather_df %>% 
  mutate(
    lagged_temp = lag(tmax),
    temp_change = tmax - lagged_temp
  ) %>% 
  filter(min_rank(temp_change) < 3)
```
## pulse data
```{r}

pulse_df =
  read_sas("data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    values_to = "bdi_score",
    names_prefix = "bdi_score_"
  )
pulse_df %>% 
  group_by(visit) %>% 
  summarize(
    mean_bdi = mean(bdi_score, na.rm =TRUE)
  ) %>% 
  knitr::kable(digits = 1)
```




